# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spikedepth',
                'doc_host': 'https://robeson1010.github.io',
                'git_url': 'https://github.com/robeson1010/spikedepth',
                'lib_path': 'spikedepth'},
  'syms': {'spikedepth.core': {'spikedepth.core.foo': ('core.html#foo', 'spikedepth/core.py')}}}
